# POST http://localhost:4000/api/signup
# Content-Type: application/json

# {
#     "fullName":"Tester",
#     "email":"tester@test.test",
#     "username":"test-user",
#     "password":"password123"
# }
GET http://localhost:4000/api/login
Content-Type: application/json

{
    "fullName":"Tester",
    "email":"tester@test.test",
    "username":"test-user",
    "password":"password123"
}